# Generated by Django 4.1.1 on 2023-04-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('location', models.IntegerField(choices=[(-1, 'Side Menu'), (0, 'USA Banks'), (1, 'Canada Banks'), (2, 'European Banks'), (3, 'Pua and Fullz')], default=-1)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Not shown but required', max_length=255)),
                ('Balance', models.CharField(blank=True, max_length=255)),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('Info', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('Status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('created',),
            },
        ),
    ]
