# Generated by Django 4.2 on 2023-04-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='location',
            field=models.IntegerField(choices=[(-1, 'Main Menu'), (0, 'USA Banks'), (1, 'Germany Banks'), (2, 'Australia Banks'), (3, 'Pua and Fullz'), (4, 'Credit Unions')], default=-1),
        ),
    ]
