# Generated by Django 4.2 on 2023-04-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_image_alter_category_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='location',
            field=models.IntegerField(choices=[(-1, 'Main Menu'), (0, 'USA Banks'), (1, 'Germany Banks'), (2, 'Australia Banks'), (3, 'Pua and Fullz'), (4, 'Canada Bank'), (5, 'Credit Unions')], default=-1),
        ),
    ]
